"""
This type stub file was generated by pyright.
"""

import logging
from stanza.models.common.trainer import Trainer as BaseTrainer
from typing import Any, Optional

"""
A trainer class to handle training and testing of models.
"""
logger = logging.getLogger('stanza')
def unpack_batch(batch, use_cuda):
    """ Unpack a batch from the data loader. """
    ...

class Trainer(BaseTrainer):
    """ A trainer for training models. """
    def __init__(self, args: Optional[Any] = ..., vocab: Optional[Any] = ..., pretrain: Optional[Any] = ..., model_file: Optional[Any] = ..., use_cuda: bool = ...):
        self.use_cuda = ...
        self.parameters = ...
        self.optimizer = ...
    
    def update(self, batch, eval: bool = ...):
        ...
    
    def predict(self, batch, unsort: bool = ...):
        ...
    
    def save(self, filename, skip_modules: bool = ...):
        ...
    
    def load(self, filename, args: Optional[Any] = ...):
        self.args = ...
        self.vocab = ...
        self.model = ...
    


