"""
This type stub file was generated by pyright.
"""

from stanza.models.common.vocab import BaseMultiVocab, BaseVocab

class TagVocab(BaseVocab):
    """ A vocab for the output tag sequence. """
    def build_vocab(self):
        ...
    


class MultiVocab(BaseMultiVocab):
    def state_dict(self):
        """ Also save a vocab name to class name mapping in state dict. """
        ...
    
    @classmethod
    def load_state_dict(cls, state_dict):
        ...
    


