"""
This type stub file was generated by pyright.
"""

import logging
from stanza.models.common.doc import *
from typing import Any, Optional

logger = logging.getLogger('stanza')
def load_mwt_dict(filename):
    ...

def process_sentence(sentence, mwt_dict: Optional[Any] = ...):
    ...

def find_token(token, text):
    """
    Robustly finds the first occurrence of token in the text, and return its offset and it's underlying original string.
    Ignores whitespace mismatches between the text and the token.
    """
    ...

def output_predictions(output_file, trainer, data_generator, vocab, mwt_dict, max_seqlen=..., orig_text: Optional[Any] = ..., no_ssplit: bool = ...):
    ...

def eval_model(args, trainer, batches, vocab, mwt_dict):
    ...

