"""
This type stub file was generated by pyright.
"""

from stanza.models.common.vocab import BaseVocab

class Vocab(BaseVocab):
    def build_vocab(self):
        ...
    
    def normalize_unit(self, unit):
        ...
    
    def normalize_token(self, token):
        ...
    


