"""
This type stub file was generated by pyright.
"""

from owlready2.util import *

class OwlReadyWarning(UserWarning):
  ...


class OwlReadyUndefinedIRIWarning(OwlReadyWarning):
  ...


class OwlReadyOntologyIRIWarning(OwlReadyWarning):
  ...


class OwlReadyMROWarning(OwlReadyWarning):
  ...


class OwlReadyGeneratedNameWarning(OwlReadyWarning):
  ...


class OwlReadyDupplicatedNameWarning(OwlReadyWarning):
  ...


class OwlReadyError(Exception):
  ...


class OwlReadySharedBlankNodeError(OwlReadyError):
  ...


class OwlReadyOntologyParsingError(OwlReadyError):
  ...


class OwlReadyInconsistentOntologyError(OwlReadyError):
  ...


class OwlReadyJavaError(OwlReadyError):
  ...


def to_literal(o):
  ...

def from_literal(o, d):
  ...

_universal_abbrev_2_iri = {  }
_universal_iri_2_abbrev = {  }
_next_abb = 1
def _universal_abbrev(iri):
  ...

owlready_python_module = _universal_abbrev("http://www.lesfleursdunormal.fr/static/_downloads/owlready_ontology.owl#python_module")
owlready_python_name = _universal_abbrev("http://www.lesfleursdunormal.fr/static/_downloads/owlready_ontology.owl#python_name")
rdf_first = _universal_abbrev("http://www.w3.org/1999/02/22-rdf-syntax-ns#first")
rdf_rest = _universal_abbrev("http://www.w3.org/1999/02/22-rdf-syntax-ns#rest")
rdf_nil = _universal_abbrev("http://www.w3.org/1999/02/22-rdf-syntax-ns#nil")
rdf_type = _universal_abbrev("http://www.w3.org/1999/02/22-rdf-syntax-ns#type")
rdf_domain = _universal_abbrev("http://www.w3.org/2000/01/rdf-schema#domain")
rdf_range = _universal_abbrev("http://www.w3.org/2000/01/rdf-schema#range")
rdfs_subclassof = _universal_abbrev("http://www.w3.org/2000/01/rdf-schema#subClassOf")
rdfs_subpropertyof = _universal_abbrev("http://www.w3.org/2000/01/rdf-schema#subPropertyOf")
owl_class = _universal_abbrev("http://www.w3.org/2002/07/owl#Class")
owl_named_individual = _universal_abbrev("http://www.w3.org/2002/07/owl#NamedIndividual")
owl_object_property = _universal_abbrev("http://www.w3.org/2002/07/owl#ObjectProperty")
owl_data_property = _universal_abbrev("http://www.w3.org/2002/07/owl#DatatypeProperty")
owl_annotation_property = _universal_abbrev("http://www.w3.org/2002/07/owl#AnnotationProperty")
owl_inverse_property = _universal_abbrev("http://www.w3.org/2002/07/owl#inverseOf")
owl_restriction = _universal_abbrev("http://www.w3.org/2002/07/owl#Restriction")
owl_onproperty = _universal_abbrev("http://www.w3.org/2002/07/owl#onProperty")
owl_onclass = _universal_abbrev("http://www.w3.org/2002/07/owl#onClass")
owl_ondatarange = _universal_abbrev("http://www.w3.org/2002/07/owl#onDataRange")
owl_cardinality = _universal_abbrev("http://www.w3.org/2002/07/owl#cardinality")
owl_min_cardinality = _universal_abbrev("http://www.w3.org/2002/07/owl#minCardinality")
owl_max_cardinality = _universal_abbrev("http://www.w3.org/2002/07/owl#maxCardinality")
SOME = _universal_abbrev("http://www.w3.org/2002/07/owl#someValuesFrom")
ONLY = _universal_abbrev("http://www.w3.org/2002/07/owl#allValuesFrom")
EXACTLY = _universal_abbrev("http://www.w3.org/2002/07/owl#qualifiedCardinality")
MIN = _universal_abbrev("http://www.w3.org/2002/07/owl#minQualifiedCardinality")
MAX = _universal_abbrev("http://www.w3.org/2002/07/owl#maxQualifiedCardinality")
VALUE = _universal_abbrev("http://www.w3.org/2002/07/owl#hasValue")
owl_unionof = _universal_abbrev("http://www.w3.org/2002/07/owl#unionOf")
owl_intersectionof = _universal_abbrev("http://www.w3.org/2002/07/owl#intersectionOf")
owl_oneof = _universal_abbrev("http://www.w3.org/2002/07/owl#oneOf")
owl_equivalentclass = _universal_abbrev("http://www.w3.org/2002/07/owl#equivalentClass")
owl_thing = _universal_abbrev("http://www.w3.org/2002/07/owl#Thing")
owl_alldisjointclasses = _universal_abbrev("http://www.w3.org/2002/07/owl#AllDisjointClasses")
owl_alldifferent = _universal_abbrev("http://www.w3.org/2002/07/owl#AllDifferent")
owl_members = _universal_abbrev("http://www.w3.org/2002/07/owl#members")
owl_distinctmembers = _universal_abbrev("http://www.w3.org/2002/07/owl#distinctMembers")
SPECIAL_ATTRS = "namespace", "name", "_name", "iri", "_iri", "storid", "is_a", "equivalent_to", "_equivalent_to", "disjoint_with", "_disjoint_with", "defined_class", "_disjoint_unions", "__class__", "__qualname__", "__module__", "__doc__", "__bases__"
SPECIAL_PROP_ATTRS = "namespace", "name", "_name", "python_name", "_python_name", "_domain", "_property_chain", "_inverse_property", "inverse_property", "inverse", "_range", "iri", "_iri", "storid", "is_a", "equivalent_to", "_equivalent_to", "disjoint_with", "_disjoint_with", "__class__", "__qualname__", "__module__", "__doc__", "__bases__"
LOADING = Environment()
_universal_abbrev_2_datatype = {  }
_universal_datatype_2_abbrev = {  }
_universal_abbrev_2_datatype_parser = {  }
_universal_datatype_2_abbrev_unparser = {  }
def _universal_abbrev_datatype(datatype, parser, unparser, *iris):
  ...

def bool_parser(s):
  ...

def bool_unparser(b):
  ...

def number_unparser(x):
  ...

def _parse_date(s):
  ...

def _parse_datetime(s):
  ...

def set_datatype_iri(datatype, iri):
  ...

owl_alldisjointproperties = _universal_abbrev("http://www.w3.org/2002/07/owl#AllDisjointProperties")
owl_equivalentproperty = _universal_abbrev("http://www.w3.org/2002/07/owl#equivalentProperty")
owl_equivalentindividual = _universal_abbrev("http://www.w3.org/2002/07/owl#sameAs")
owl_ontology = _universal_abbrev("http://www.w3.org/2002/07/owl#Ontology")
owl_imports = _universal_abbrev("http://www.w3.org/2002/07/owl#imports")
owl_nothing = _universal_abbrev("http://www.w3.org/2002/07/owl#Nothing")
owl_axiom = _universal_abbrev("http://www.w3.org/2002/07/owl#Axiom")
owl_annotatedsource = _universal_abbrev("http://www.w3.org/2002/07/owl#annotatedSource")
owl_annotatedproperty = _universal_abbrev("http://www.w3.org/2002/07/owl#annotatedProperty")
owl_annotatedtarget = _universal_abbrev("http://www.w3.org/2002/07/owl#annotatedTarget")
owl_complementof = _universal_abbrev("http://www.w3.org/2002/07/owl#complementOf")
owl_disjointwith = _universal_abbrev("http://www.w3.org/2002/07/owl#disjointWith")
owl_propdisjointwith = _universal_abbrev("http://www.w3.org/2002/07/owl#propertyDisjointWith")
rdfs_datatype = _universal_abbrev("http://www.w3.org/2000/01/rdf-schema#Datatype")
owl_ondatatype = _universal_abbrev("http://www.w3.org/2002/07/owl#onDatatype")
owl_withrestrictions = _universal_abbrev("http://www.w3.org/2002/07/owl#withRestrictions")
xmls_length = _universal_abbrev("http://www.w3.org/2001/XMLSchema#length")
xmls_minlength = _universal_abbrev("http://www.w3.org/2001/XMLSchema#minLength")
xmls_maxlength = _universal_abbrev("http://www.w3.org/2001/XMLSchema#maxLength")
xmls_pattern = _universal_abbrev("http://www.w3.org/2001/XMLSchema#pattern")
xmls_whitespace = _universal_abbrev("http://www.w3.org/2001/XMLSchema#whiteSpace")
xmls_maxinclusive = _universal_abbrev("http://www.w3.org/2001/XMLSchema#maxInclusive")
xmls_maxexclusive = _universal_abbrev("http://www.w3.org/2001/XMLSchema#maxExclusive")
xmls_mininclusive = _universal_abbrev("http://www.w3.org/2001/XMLSchema#minInclusive")
xmls_minexclusive = _universal_abbrev("http://www.w3.org/2001/XMLSchema#minExclusive")
xmls_totaldigits = _universal_abbrev("http://www.w3.org/2001/XMLSchema#totalDigits")
xmls_fractiondigits = _universal_abbrev("http://www.w3.org/2001/XMLSchema#fractionDigits")
owl_propertychain = _universal_abbrev("http://www.w3.org/2002/07/owl#propertyChainAxiom")
HAS_SELF = _universal_abbrev("http://www.w3.org/2002/07/owl#hasSelf")
owlready_class_property_type = _universal_abbrev("http://www.lesfleursdunormal.fr/static/_downloads/owlready_ontology.owl#class_property_type")
owlready_defined_class = _universal_abbrev("http://www.lesfleursdunormal.fr/static/_downloads/owlready_ontology.owl#defined_class")
rdf_property = _universal_abbrev("http://www.w3.org/1999/02/22-rdf-syntax-ns#Property")
swrl_variable = _universal_abbrev("http://www.w3.org/2003/11/swrl#Variable")
swrl_imp = _universal_abbrev("http://www.w3.org/2003/11/swrl#Imp")
swrl_body = _universal_abbrev("http://www.w3.org/2003/11/swrl#body")
swrl_head = _universal_abbrev("http://www.w3.org/2003/11/swrl#head")
swrl_class_atom = _universal_abbrev("http://www.w3.org/2003/11/swrl#ClassAtom")
swrl_class_predicate = _universal_abbrev("http://www.w3.org/2003/11/swrl#classPredicate")
swrl_dataprop_atom = _universal_abbrev("http://www.w3.org/2003/11/swrl#DatavaluedPropertyAtom")
swrl_objprop_atom = _universal_abbrev("http://www.w3.org/2003/11/swrl#IndividualPropertyAtom")
swrl_property_predicate = _universal_abbrev("http://www.w3.org/2003/11/swrl#propertyPredicate")
swrl_builtin_atom = _universal_abbrev("http://www.w3.org/2003/11/swrl#BuiltinAtom")
swrl_builtin = _universal_abbrev("http://www.w3.org/2003/11/swrl#builtin")
swrl_datarange_atom = _universal_abbrev("http://www.w3.org/2003/11/swrl#DataRangeAtom")
swrl_datarange = _universal_abbrev("http://www.w3.org/2003/11/swrl#dataRange")
swrl_argument1 = _universal_abbrev("http://www.w3.org/2003/11/swrl#argument1")
swrl_argument2 = _universal_abbrev("http://www.w3.org/2003/11/swrl#argument2")
swrl_arguments = _universal_abbrev("http://www.w3.org/2003/11/swrl#arguments")
swrl_equivalentindividual = _universal_abbrev("http://www.w3.org/2003/11/swrl#SameIndividualAtom")
swrl_differentfrom = _universal_abbrev("http://www.w3.org/2003/11/swrl#DifferentIndividualsAtom")
owl_bottomobjectproperty = _universal_abbrev("http://www.w3.org/2002/07/owl#bottomObjectProperty")
owl_bottomdataproperty = _universal_abbrev("http://www.w3.org/2002/07/owl#bottomDataProperty")
owl_disjointunion = _universal_abbrev("http://www.w3.org/2002/07/owl#disjointUnionOf")
owlready_concrete = _universal_abbrev("http://www.lesfleursdunormal.fr/static/_downloads/owlready_ontology.owl#concrete")
issubclass_python = issubclass
