"""
This type stub file was generated by pyright.
"""

from owlready2.namespace import *
from owlready2.entity import *
from owlready2.prop import *
from owlready2.individual import *
from owlready2.class_construct import *
from typing import Any, Optional

def close_world(self, Properties: Optional[Any] = ..., close_instance_list: bool = ..., recursive: bool = ...):
  ...

