"""
This type stub file was generated by pyright.
"""

"""ntriples_diff.py

Compute the differences between 2 NTriples files. Take care of symmetric relations
and different blank node naming.

Usage:

  ntriple_diff.py onto.nt : canonize the NTriples file.

  ntriple_diff.py onto1.nt onto2.nt : compare the two NTriples files.

Options:

  --short : shortify IRI and literal (more Human readable).
"""
def shortify(triples):
  ...

symmetric_predicates = "<http://www.w3.org/2002/07/owl#complementOf>", "<http://www.w3.org/2002/07/owl#inverseOf>", "<http://www.w3.org/2002/07/owl#equivalentClass>", "<http://www.w3.org/2002/07/owl#equivalentProperty>", "<http://www.w3.org/2002/07/owl#sameAs>", "<http://www.w3.org/2002/07/owl#disjointWith>"
useless_triples = ("<http://www.w3.org/1999/02/22-rdf-syntax-ns#PlainLiteral>", "<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>", "<http://www.w3.org/2000/01/rdf-schema#Datatype>"), ("<http://www.w3.org/2000/01/rdf-schema#Literal>", "<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>", "<http://www.w3.org/2000/01/rdf-schema#Datatype>"), ("<http://www.w3.org/2001/XMLSchema#float>", "<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>", "<http://www.w3.org/2000/01/rdf-schema#Datatype>"), ("<http://www.w3.org/2001/XMLSchema#integer>", "<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>", "<http://www.w3.org/2000/01/rdf-schema#Datatype>"), ("<http://www.w3.org/2001/XMLSchema#nonNegativeInteger>", "<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>", "<http://www.w3.org/2000/01/rdf-schema#Datatype>"), ("<http://www.w3.org/2001/XMLSchema#string>", "<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>", "<http://www.w3.org/2000/01/rdf-schema#Datatype>")
class Blank(object):
  def __init__(self):
    self.triples = ...
    self.name = ...
  
  def add_triple(self, s, p, o):
    ...
  
  def get_name(self):
    ...
  


def canonize(nt):
  ...

def diff(nt1, nt2):
  ...

if __name__ == "__main__":
  ...
