"""
This type stub file was generated by pyright.
"""

from rdflib import XSD

"""
Utility functions for supporting the XML Schema Datatypes hierarchy
"""
XSD_DTs = set((XSD.integer, XSD.decimal, XSD.float, XSD.double, XSD.string, XSD.boolean, XSD.dateTime, XSD.nonPositiveInteger, XSD.negativeInteger, XSD.long, XSD.int, XSD.short, XSD.byte, XSD.nonNegativeInteger, XSD.unsignedLong, XSD.unsignedInt, XSD.unsignedShort, XSD.unsignedByte, XSD.positiveInteger, XSD.date))
_sub_types = { XSD.integer: [XSD.nonPositiveInteger, XSD.negativeInteger, XSD.long, XSD.int, XSD.short, XSD.byte, XSD.nonNegativeInteger, XSD.positiveInteger, XSD.unsignedLong, XSD.unsignedInt, XSD.unsignedShort, XSD.unsignedByte] }
_super_types = {  }
_typePromotionMap = { XSD.float: { XSD.integer: XSD.float,XSD.decimal: XSD.float,XSD.double: XSD.double },XSD.double: { XSD.integer: XSD.double,XSD.float: XSD.double,XSD.decimal: XSD.double },XSD.decimal: { XSD.integer: XSD.decimal,XSD.float: XSD.float,XSD.double: XSD.double },XSD.integer: { XSD.decimal: XSD.decimal,XSD.float: XSD.float,XSD.double: XSD.double } }
def type_promotion(t1, t2):
    ...

