"""
This type stub file was generated by pyright.
"""

def _diff(a, b, expr):
    ...

def _minus(a, b):
    ...

def _join(a, b):
    ...

def _ebv(expr, ctx):
    """
    Return true/false for the given expr
    Either the expr is itself true/false
    or evaluates to something, with the given ctx

    an error is false
    """
    ...

def _eval(expr, ctx, raise_not_bound_error: bool = ...):
    ...

def _filter(a, expr):
    ...

def _fillTemplate(template, solution):
    """
    For construct/deleteWhere and friends

    Fill a triple template with instantiated variables
    """
    ...

def _val(v):
    """ utilitity for ordering things"""
    ...

