"""
This type stub file was generated by pyright.
"""

from rdflib.query import Processor, Result, UpdateProcessor
from typing import Any, Optional

"""
Code for tying SPARQL Engine into RDFLib

These should be automatically registered with RDFLib

"""
def prepareQuery(queryString, initNs=..., base: Optional[Any] = ...):
    """
    Parse and translate a SPARQL Query
    """
    ...

def processUpdate(graph, updateString, initBindings=..., initNs=..., base: Optional[Any] = ...):
    """
    Process a SPARQL Update Request
    returns Nothing on success or raises Exceptions on error
    """
    ...

class SPARQLResult(Result):
    def __init__(self, res):
        self.vars = ...
        self.bindings = ...
        self.askAnswer = ...
        self.graph = ...
    


class SPARQLUpdateProcessor(UpdateProcessor):
    def __init__(self, graph):
        self.graph = ...
    
    def update(self, strOrQuery, initBindings=..., initNs=...):
        ...
    


class SPARQLProcessor(Processor):
    def __init__(self, graph):
        self.graph = ...
    
    def query(self, strOrQuery, initBindings=..., initNs=..., base: Optional[Any] = ..., DEBUG: bool = ...):
        """
        Evaluate a query with the given initial bindings, and initial
        namespaces. The given base is used to resolve relative URIs in
        the query and will be overridden by any BASE given in the query.
        """
        ...
    


