"""
This type stub file was generated by pyright.
"""

"""

Code for carrying out Update Operations

"""
def _graphOrDefault(ctx, g):
    ...

def _graphAll(ctx, g):
    """
    return a list of graphs
    """
    ...

def evalLoad(ctx, u):
    """
    http://www.w3.org/TR/sparql11-update/#load
    """
    ...

def evalCreate(ctx, u):
    """
    http://www.w3.org/TR/sparql11-update/#create
    """
    ...

def evalClear(ctx, u):
    """
    http://www.w3.org/TR/sparql11-update/#clear
    """
    ...

def evalDrop(ctx, u):
    """
    http://www.w3.org/TR/sparql11-update/#drop
    """
    ...

def evalInsertData(ctx, u):
    """
    http://www.w3.org/TR/sparql11-update/#insertData
    """
    ...

def evalDeleteData(ctx, u):
    """
    http://www.w3.org/TR/sparql11-update/#deleteData
    """
    ...

def evalDeleteWhere(ctx, u):
    """
    http://www.w3.org/TR/sparql11-update/#deleteWhere
    """
    ...

def evalModify(ctx, u):
    ...

def evalAdd(ctx, u):
    """

    add all triples from src to dst

    http://www.w3.org/TR/sparql11-update/#add
    """
    ...

def evalMove(ctx, u):
    """

    remove all triples from dst
    add all triples from src to dst
    remove all triples from src

    http://www.w3.org/TR/sparql11-update/#move
    """
    ...

def evalCopy(ctx, u):
    """

    remove all triples from dst
    add all triples from src to dst

    http://www.w3.org/TR/sparql11-update/#copy
    """
    ...

def evalUpdate(graph, update, initBindings=...):
    """

    http://www.w3.org/TR/sparql11-update/#updateLanguage

    'A request is a sequence of operations [...] Implementations MUST
    ensure that operations of a single request are executed in a
    fashion that guarantees the same effects as executing them in
    lexical order.

    Operations all result either in success or failure.

    If multiple operations are present in a single request, then a
    result of failure from any operation MUST abort the sequence of
    operations, causing the subsequent operations to be ignored.'

    This will return None on success and raise Exceptions on error

    """
    ...

