"""
This type stub file was generated by pyright.
"""

from .db import database_sync_to_async

def get_handler_name(message):
    """
    Looks at a message, checks it has a sensible type, and returns the
    handler name for that type.
    """
    ...

class AsyncConsumer:
    """
    Base consumer class. Implements the ASGI application spec, and adds on
    channel layer management and routing of events to named methods based
    on their type.
    """
    _sync = ...
    channel_layer_alias = ...
    def __init__(self, scope):
        self.scope = ...
    
    async def __call__(self, receive, send):
        """
        Dispatches incoming messages to type-based handlers asynchronously.
        """
        self.channel_layer = ...
    
    async def dispatch(self, message):
        """
        Works out what to do with a message.
        """
        ...
    
    async def send(self, message):
        """
        Overrideable/callable-by-subclasses send method.
        """
        ...
    


class SyncConsumer(AsyncConsumer):
    """
    Synchronous version of the consumer, which is what we write most of the
    generic consumers against (for now). Calls handlers in a threadpool and
    uses CallBouncer to get the send method out to the main event loop.

    It would have been possible to have "mixed" consumers and auto-detect
    if a handler was awaitable or not, but that would have made the API
    for user-called methods very confusing as there'd be two types of each.
    """
    _sync = ...
    @database_sync_to_async
    def dispatch(self, message):
        """
        Dispatches incoming messages to type-based handlers asynchronously.
        """
        ...
    
    def send(self, message):
        """
        Overrideable/callable-by-subclasses send method.
        """
        ...
    


