"""
This type stub file was generated by pyright.
"""

def name_that_thing(thing):
    """
    Returns either the function/class path or just the object's repr
    """
    ...

async def await_many_dispatch(consumer_callables, dispatch):
    """
    Given a set of consumer callables, awaits on them all and passes results
    from them to the dispatch awaitable as they come in.
    """
    ...

