"""
This type stub file was generated by pyright.
"""

import enum
from typing import Any

class ChoicesMeta(enum.EnumMeta):
    def __contains__(self, item: Any) -> bool:
        ...
    


class Choices(enum.Enum, metaclass=ChoicesMeta):
    def __str__(self):
        ...
    


class _IntegerChoicesMeta(ChoicesMeta):
    ...


class IntegerChoices(int, Choices, metaclass=_IntegerChoicesMeta):
    ...


class _TextChoicesMeta(ChoicesMeta):
    ...


class TextChoices(str, Choices, metaclass=_TextChoicesMeta):
    ...


