"""
This type stub file was generated by pyright.
"""

import logging.config
from stanza.pipeline.core import Pipeline
from stanza.models.common.doc import Document
from stanza.utils.resources import download
from stanza._version import __resources_version__, __version__

