"""
This type stub file was generated by pyright.
"""

from typing import List, Optional
from django.template.base import Origin, Template
from django.template.engine import Engine

class Loader:
    def __init__(self, engine: Engine) -> None:
        ...
    
    def get_template(self, template_name: str, skip: Optional[List[Origin]] = ...) -> Template:
        ...
    
    def get_template_sources(self, template_name: str) -> None:
        ...
    
    def reset(self) -> None:
        ...
    


