"""
This type stub file was generated by pyright.
"""

from stanza.protobuf import CorefChain, DependencyGraph, Document, Entity, IndexedWord, MapIntString, MapStringString, Mention, NERMention, Operator, ParseTree, Polarity, Quote, Relation, RelationTriple, Sentence, SentenceFragment, Span, SpeakerInfo, Timex, Token, TokenLocation, to_text
from .client import AnnotationException, CoreNLPClient, TimeoutException
from .annotator import Annotator

