"""
This type stub file was generated by pyright.
"""

import logging
import torch
from .vocab import BaseVocab
from typing import Any, Optional

"""
Supports for pretrained data.
"""
logger = logging.getLogger('stanza')
class PretrainedWordVocab(BaseVocab):
    def build_vocab(self):
        ...
    


class Pretrain:
    """ A loader and saver for pretrained embeddings. """
    def __init__(self, filename: Optional[Any] = ..., vec_filename: Optional[Any] = ..., max_vocab=..., save_to_file: bool = ...):
        self.filename = ...
    
    @property
    def vocab(self):
        ...
    
    @property
    def emb(self):
        ...
    
    def load(self):
        ...
    
    def read_pretrain(self):
        ...
    
    def read_from_file(self, filename, open_func=...):
        """
        Open a vector file using the provided function and read from it.
        """
        ...
    


if __name__ == '__main__':
    pretrain = Pretrain('test.pt', 'test.txt')
    x = torch.load('test.pt')
    pretrain = Pretrain('test.pt', 'test.txt')
