"""
This type stub file was generated by pyright.
"""

class Trainer:
    def change_lr(self, new_lr):
        ...
    
    def save(self, filename):
        ...
    
    def load(self, filename):
        ...
    


