"""
This type stub file was generated by pyright.
"""

"""
Utilities for calculating edits between word and lemma forms.
"""
EDIT_TO_ID = { 'none': 0,'identity': 1,'lower': 2 }
def get_edit_type(word, lemma):
    """ Calculate edit types. """
    ...

def edit_word(word, pred, edit_id):
    """
    Edit a word, given edit and seq2seq predictions.
    """
    ...

