"""
This type stub file was generated by pyright.
"""

from stanza.models.common.vocab import BaseMultiVocab, BaseVocab

class Vocab(BaseVocab):
    def build_vocab(self):
        ...
    


class MultiVocab(BaseMultiVocab):
    @classmethod
    def load_state_dict(cls, state_dict):
        ...
    


