"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict, List, Optional, Union
from django.template.defaulttags import TemplateLiteral

_Token = Union[List[int], int, str]
class TokenBase:
    def nud(self, parser: Any) -> None:
        ...
    
    def led(self, left: Any, parser: Any) -> None:
        ...
    
    def display(self):
        ...
    


def infix(bp: Any, func: Any):
    ...

def prefix(bp: Any, func: Any):
    ...

OPERATORS: Any
class Literal(TokenBase):
    def __init__(self, value: Optional[_Token]) -> None:
        ...
    
    def display(self):
        ...
    
    def eval(self, context: Dict[Any, Any]) -> Optional[_Token]:
        ...
    


class EndToken(TokenBase):
    def nud(self, parser: Any) -> None:
        ...
    


class IfParser:
    def __init__(self, tokens: List[Optional[_Token]]) -> None:
        ...
    
    def translate_token(self, token: Optional[_Token]) -> Literal:
        ...
    
    def next_token(self) -> Literal:
        ...
    
    def parse(self) -> TemplateLiteral:
        ...
    
    def expression(self, rbp: int = ...) -> Literal:
        ...
    
    def create_var(self, value: Optional[_Token]) -> Literal:
        ...
    


