"""
This type stub file was generated by pyright.
"""

import logging
from typing import Any, Optional

"""
A trainer class to handle training and testing of models.
"""
logger = logging.getLogger('stanza')
def unpack_batch(batch, use_cuda):
    """ Unpack a batch from the data loader. """
    ...

class Trainer(object):
    """ A trainer for training models. """
    def __init__(self, args: Optional[Any] = ..., vocab: Optional[Any] = ..., emb_matrix: Optional[Any] = ..., model_file: Optional[Any] = ..., use_cuda: bool = ...):
        self.use_cuda = ...
    
    def update(self, batch, eval: bool = ...):
        ...
    
    def predict(self, batch, unsort: bool = ...):
        ...
    
    def train_dict(self, pairs):
        """ Train a MWT expander given training word-expansion pairs. """
        ...
    
    def predict_dict(self, words):
        """ Predict a list of expansions given words. """
        ...
    
    def ensemble(self, cands, other_preds):
        """ Ensemble the dict with statistical model predictions. """
        ...
    
    def save(self, filename):
        ...
    
    def load(self, filename, use_cuda: bool = ...):
        self.args = ...
        self.expansion_dict = ...
        self.vocab = ...
    


