"""
This type stub file was generated by pyright.
"""

from stanza.models.common.vocab import BaseMultiVocab, BaseVocab, CompositeVocab
from typing import Any, Optional

class CharVocab(BaseVocab):
    def build_vocab(self):
        ...
    


class WordVocab(BaseVocab):
    def __init__(self, data: Optional[Any] = ..., lang=..., idx=..., cutoff=..., lower: bool = ..., ignore=...):
        self.ignore = ...
    
    def id2unit(self, id):
        ...
    
    def unit2id(self, unit):
        ...
    
    def build_vocab(self):
        ...
    


class XPOSVocab(CompositeVocab):
    def __init__(self, data: Optional[Any] = ..., lang=..., idx=..., sep=..., keyed: bool = ...):
        ...
    


class FeatureVocab(CompositeVocab):
    def __init__(self, data: Optional[Any] = ..., lang=..., idx=..., sep=..., keyed: bool = ...):
        ...
    


class MultiVocab(BaseMultiVocab):
    def state_dict(self):
        """ Also save a vocab name to class name mapping in state dict. """
        ...
    
    @classmethod
    def load_state_dict(cls, state_dict):
        ...
    


