"""
This type stub file was generated by pyright.
"""

from stanza.pipeline._constants import *
from stanza.pipeline.processor import UDProcessor

"""
Processor for performing lemmatization
"""
class LemmaProcessor(UDProcessor):
    PROVIDES_DEFAULT = ...
    REQUIRES_DEFAULT = ...
    DEFAULT_BATCH_SIZE = ...
    def __init__(self, config, pipeline, use_gpu):
        ...
    
    @property
    def use_identity(self):
        ...
    
    def _set_up_model(self, config, use_gpu):
        ...
    
    def _set_up_requires(self):
        ...
    
    def process(self, document):
        ...
    


