"""
This type stub file was generated by pyright.
"""

import logging
from stanza.pipeline._constants import *
from stanza.pipeline.processor import UDProcessor

"""
Processor for performing named entity tagging.
"""
logger = logging.getLogger('stanza')
class NERProcessor(UDProcessor):
    PROVIDES_DEFAULT = ...
    REQUIRES_DEFAULT = ...
    def _set_up_model(self, config, use_gpu):
        ...
    
    def process(self, document):
        ...
    


