"""
This type stub file was generated by pyright.
"""

from typing import Any, Optional

def make_table(header, content, column_width: Optional[Any] = ...):
    '''
    Input:
    header -> List[str]: table header
    content -> List[List[str]]: table content
    column_width -> int: table column width; set to None for dynamically calculated widths
    
    Output:
    table_str -> str: well-formatted string for the table
    '''
    ...

