"""
This type stub file was generated by pyright.
"""

import argparse
import sys

def para_to_chunks(text, char_level_pred):
    ...

def paras_to_chunks(text, char_level_pred):
    ...

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    args = parser.parse_args()
    output = sys.stdout if args.output is None else open(args.output, 'w')
