"""
This type stub file was generated by pyright.
"""

import os
import logging
from pathlib import Path
from stanza.pipeline._constants import DEPPARSE, LEMMA, MWT, NER, POS, TOKENIZE
from typing import Any, Optional

"""
utilities for getting resources
"""
logger = logging.getLogger('stanza')
HOME_DIR = str(Path.home())
DEFAULT_RESOURCES_URL = 'https://raw.githubusercontent.com/stanfordnlp/stanza-resources/master'
DEFAULT_MODEL_DIR = os.path.join(HOME_DIR, 'stanza_resources')
PIPELINE_NAMES = [TOKENIZE, MWT, POS, LEMMA, DEPPARSE, NER]
def build_default_config(resources, lang, dir, load_list):
    ...

def ensure_dir(dir):
    ...

def get_md5(path):
    ...

def unzip(dir, filename):
    ...

def is_file_existed(path, md5):
    ...

def download_file(url, path):
    ...

def request_file(url, path, md5: Optional[Any] = ...):
    ...

def sort_processors(processor_list):
    ...

def maintain_processor_list(resources, lang, package, processors):
    ...

def add_dependencies(resources, lang, processor_list):
    ...

def flatten_processor_list(processor_list):
    ...

def set_logging_level(logging_level, verbose):
    ...

def process_pipeline_parameters(lang, dir, package, processors):
    ...

def download(lang=..., dir=..., package=..., processors=..., logging_level=..., verbose: Optional[Any] = ...):
    ...

