"""
This type stub file was generated by pyright.
"""

"""
Utilities related to using spaCy in the pipeline.
"""
def check_spacy():
    """
    Import necessary components from spaCy to perform tokenization.
    """
    ...

class SpacyTokenizer:
    def __init__(self, lang=...):
        """ Construct a spaCy-based tokenizer by loading the spaCy pipeline.
        """
        self.nlp = ...
    
    def tokenize(self, text):
        """ Tokenize a document with the spaCy tokenizer and wrap the results into a Doc object.
        """
        ...
    


